version: "3.7"

services:
  app:
    image: 300237359268.dkr.ecr.ap-southeast-1.amazonaws.com/ntubot:latest
    container_name: ntubot
    env_file: .env
    command: ["python", "app.py"]

  api:
    image: 300237359268.dkr.ecr.ap-southeast-1.amazonaws.com/ntuapi:latest
    container_name: ntuapi
    env_file: .env
    ports:
      - 3000:3000
