version: "3.7"

services:
  app:
    image: 300237359268.dkr.ecr.ap-southeast-1.amazonaws.com/ntubot:latest
    container_name: ntubot
    env_file: .env
    command: ["python", "app.py"]

  api:
    image: node:17-alpine
    container_name: ntubot-api
    env_file: .env
    command: ["sh", "-c", "npm start"]
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
